package com.streamverse.pipeline.config

data class PipelineConfig(
    val githubToken: String = System.getenv("GH_PAT") ?: System.getenv("STREAMVERSE_DATA_TOKEN") ?: "",
    val dataRepoUrl: String = System.getenv("DATA_BASE_URL") ?: "https://Goddiewayne.github.io/streamverse-data",
    val dataRepoRemote: String = System.getenv("DATA_REPO_REMOTE") ?: "https://github.com/Goddiewayne/streamverse-data.git",
    val dataRepoBranch: String = System.getenv("DATA_REPO_BRANCH") ?: "gh-pages",
    val outputDir: String = System.getenv("OUTPUT_DIR") ?: "build/catalogue",
    val stateDir: String = System.getenv("STATE_DIR") ?: "build/state",
    val logDir: String = System.getenv("LOG_DIR") ?: "logs",
    val maxConcurrentProbes: Int = (System.getenv("MAX_CONCURRENT_PROBES") ?: "50").toInt(),
    val probeTimeoutMs: Long = (System.getenv("PROBE_TIMEOUT_MS") ?: "15000").toLong(),
    val probeConnectTimeoutMs: Long = (System.getenv("PROBE_CONNECT_TIMEOUT_MS") ?: "5000").toLong(),
    val probeReadTimeoutMs: Long = (System.getenv("PROBE_READ_TIMEOUT_MS") ?: "10000").toLong(),
    val adaptiveProbeMinIntervalMs: Long = (System.getenv("ADAPTIVE_PROBE_MIN_INTERVAL_MS") ?: "300000").toLong(),
    val adaptiveProbeMaxIntervalMs: Long = (System.getenv("ADAPTIVE_PROBE_MAX_INTERVAL_MS") ?: "86400000").toLong(),
    val healthyThreshold: Int = (System.getenv("HEALTHY_THRESHOLD") ?: "3").toInt(),
    val unhealthyThreshold: Int = (System.getenv("UNHEALTHY_THRESHOLD") ?: "5").toInt(),
    val catalogueVersion: Int = (System.getenv("CATALOGUE_VERSION") ?: "1").toInt(),
    val generateCompressedArtifacts: Boolean = System.getenv("GENERATE_COMPRESSED") != "false",
    val generateIncrementalDiffs: Boolean = System.getenv("GENERATE_DIFFS") != "false",
    val dryRun: Boolean = System.getenv("DRY_RUN") == "true",
    val skipProbe: Boolean = System.getenv("SKIP_PROBE") == "true",
    val workers: Int = (System.getenv("WORKERS") ?: "4").toInt(),
    val probeWorkerPoolSize: Int = (System.getenv("PROBE_WORKER_POOL_SIZE") ?: "10").toInt(),
    val probeQueueCapacity: Int = (System.getenv("PROBE_QUEUE_CAPACITY") ?: "10000").toInt(),
    val stateSnapshotIntervalMs: Long = (System.getenv("STATE_SNAPSHOT_INTERVAL_MS") ?: "60000").toLong(),
    val enableMetrics: Boolean = System.getenv("ENABLE_METRICS") != "false",
)
